<?= $this->doctype() ?>

<html lang="en" class="wh100">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Relay Programing')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/syntaxhighlighter/shCoreDefault.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
                    ->prependFile($this->basePath() . '/js/app.js')
                    ->prependFile($this->basePath() . '/js/jquery.cookie.js')

                    ->prependFile($this->basePath() . '/js/syntaxhighlighter/shBrushCss.js')
                    ->prependFile($this->basePath() . '/js/syntaxhighlighter/shBrushXml.js')

                    ->prependFile($this->basePath() . '/js/syntaxhighlighter/shBrushRuby.js')
                    ->prependFile($this->basePath() . '/js/syntaxhighlighter/shBrushPython.js')
                    ->prependFile($this->basePath() . '/js/syntaxhighlighter/shBrushPerl.js')
                    ->prependFile($this->basePath() . '/js/syntaxhighlighter/shBrushPhp.js')
                    ->prependFile($this->basePath() . '/js/syntaxhighlighter/shBrushJScript.js')
                    ->prependFile($this->basePath() . '/js/syntaxhighlighter/shBrushJava.js')
                    ->prependFile($this->basePath() . '/js/syntaxhighlighter/shBrushCSharp.js')
                    ->prependFile($this->basePath() . '/js/syntaxhighlighter/shBrushCpp.js')

                    ->prependFile($this->basePath() . '/js/syntaxhighlighter/shCore.js')

                    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                    ->prependFile($this->basePath() . '/js/jquery.min.js')
                    ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                    ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

  </head>
  <body class="wh100">
    <div class="container bb wh100">
      <?= $this->content; ?>
    </div>
    <?= $this->inlineScript() ?>
    <script>
      SyntaxHighlighter.config.bloggerMode = true;
    </script>
  </body>
</html>
