<div id="sign_up">
  <div class="wrapper">
    <div class="filter"></div>
    <div id="sign_up_lightbox" class="lightbox br">
      <div class="header">
        <div class="title">入室</div>
      </div>
      <form id="sign_up_form" class="body">
        <div class="title">name:</div>
        <div class="input_name">
          <input type="text" maxlength="8" name="name" class="br" />
        </div>
        <div class="input_color">
          <input type="color" value="#d9534f" name="color" list="color-list" />
          <datalist id="color-list">
            <option value="#d9534f"></option>
            <option value="#f47c3c"></option>
            <option value="#29abe0"></option>
            <option value="#93c54b"></option>
            <option value="#325d88"></option>
          </datalist>
        </div>
        <div class="join_button">
          <input id="join" class="button br" type="submit" value="JOIN" />
        </div>
      </div>
    </div>
  </div>
</div>
