<div id="login">
  <div class="wrapper">
    <div class="filter"></div>
    <div id="login_lightbox" class="lightbox br">
      <div class="header">
        <div class="title">入室</div>
      </div>
      <div class="body">
        <div class="title">name:</div>
        <div class="input_name">
          <input type="text" maxlength="10" class="br" />
        </div>
        <div class="input_color">
          <input type="color" value="#ffffff" />
        </div>
        <div id="join" class="button br">JOIN</div>
      </div>
    </div>
  </div>
</div>
