<div id="login">
  <div class="wrapper">
    <div class="filter"></div>
    <div id="login_lightbox" class="lightbox br">
      <div class="header">
        <div class="title">入室</div>
      </div>
      <form id="login_form" class="body">
        <div class="title">name:</div>
        <div class="input_name">
          <input type="text" maxlength="10" name="name" class="br" />
        </div>
        <div class="input_color">
          <input type="color" value="#ffffff" name="color" />
        </div>
        <div class="join_button">
          <input id="join" class="button br" type="submit" value="JOIN" />
        </div>
      </div>
    </div>
  </div>
</div>
