<form id="user_input_form">
  <div id="user_input_wrapper">
    <div id="user_ico_field">
      <div id="user_ico" class="br">User1</div>
    </div>
    <div id="user_input_field">
      <input class="br" name="text" autocomplete="off" />
    </div>
    <div id="user_input_btnSp">
      <input id="submitBtn" class="button br" type="submit" value="投稿" />
      <div id="runBtn" class="button br">RUN</div>
    </div>
  </div>
</form>
