<form id="user_input_form">
  <div id="user_input_wrapper">
    <div id="user_ico_field">
      <div id="user_ico" class="br"></div>
    </div>
    <div id="user_input_field">
      <input class="br" name="text" autocomplete="off" maxlength="30" />
    </div>
    <div id="user_input_btnSp">
      <input id="submitBtn" class="button br" type="submit" value="POST" />
      <a href="http://ideone.com/" id="runBtn" class="button br" target="_blank">RUN</a>
    </div>
  </div>
</form>
