<form id="user_input_form">
  <div id="user_input_wrapper">
    <div id="user_ico_field">
      <div id="user_ico" class="br button"></div>
      <div id="user_info_lb" class="br bb">
        <div class="wrapper">
          <div class="header">Relay Programing</div>
          <div class="body">
            <div class="user_info_row">
              <div class="title">行番号表示切り替え</div>
              <div class="body">
                <div id="showLineNumBtn" class="br bb button"></div>
              </div>
            </div>
            <div id="signOutBtn" class="br bb button">SIGN OUT</div>
          </div>
          <div class="footer">Copyright (C) 2016 Hisa Kouki All Rights Reserved.</div>
        </div>
      </div>
    </div>
    <div id="user_input_field">
      <input class="br" name="text" autocomplete="off" maxlength="100" />
    </div>
    <div id="user_input_btnSp">
      <input id="submitBtn" style="display:none" type="submit" value="POST" />
      <a href="http://ideone.com/" id="runBtn" class="btn btn-success" target="_blank">RUN</a>
    </div>
  </div>
</form>
