<div id="app-body" class="wh100 exist_ui">

  <div id="code_chat_view" class="wh100">
    <!-- area for coded text -->
    <?= $this->code_view ?>

    <!-- area for chat text -->
    <?= $this->chat_view ?>

    <!-- area for members -->
    <?= $this->members_view ?>
  </div>

  <!-- area for user input -->
  <?= $this->user_input ?>
</div>

<!-- Login lightbox -->
<?= $this->loginlb ?>

<input id="room_id" type="hidden" value="<?= $this->room_id ?>" />




<?php
$api_user = $this->url('api/default', array('controller' => 'user'));
$api_code = $this->url('api/default', array('controller' => 'code'));

$this->inlineScript()->appendScript(
<<<__END__

/* declare members */
var \$signUpDOM = \$("#sign_up"),
    \$signUpForm = \$("#sign_up_form"),
    \$codeViewDOM = \$("#code_view"),
    userId = -1,
    roomId = \$("#room_id").val(),
    userIdCN = "RPRoom" + roomId + "Uid",
    userName = "",
    userColor = "#ffffff";
/* end declare members */

/* init */
(function init(){
  if($.cookie(userIdCN) > 0){
    userId = $.cookie(userIdCN);
    signIn();
    return;
  }
  setLoginEvent();
})();
/* end init */


/* login */
function setLoginEvent(){
  \$signUpForm.on("submit", function(_e){
    _e.preventDefault();
    signUp();
    return false;
  });
}

function signUp(){
  var name = \$signUpForm.find('.input_name > input').val(),
      color = \$signUpForm.find('.input_color > input').val();
  log("user inputs", name, color, roomId);

  var postData = { "type": "signUp", "name": name, "color": color, "room_id": roomId };
  post({"url": "$api_user", "type": "post", "query": postData,
    "success": function(_data){
      log("success signUp", _data);
      succeedSignUp(_data['data']);
    },
    "fail": function(_data){
      log("fail signUp", _data);
      failedSignUp();
    },
    "complete": function(_data){ /* nothing to do. */ }
  });
}

function succeedSignUp(_user){
  /* set User Id */
  log("user", _user);
  userId = +_user['id'];
  $.cookie(userIdCN, userId, { "expires": 1 });
  /* end set User Id */

  signIn();
}
function failedSignUp(){ alert("Failed to create or sign up."); }

function signIn(){
  var postData = { "type": "signIn", "user_id": userId, "room_id": roomId };
  post({"url": "$api_user", "type": "post", "query": postData,
    "success": function(_data){
      log("success signIn", _data);
      succeedSignIn(_data['data']);
    },
    "fail": function(_data){
      log("fail signIn", _data);
      alert("Failed Sign In.");
    },
    "complete": function(_data){ /* nothing to do. */ }
  });
}

function succeedSignIn(_user){
  /* set User Info */
  log("user", _user);
  userId = +_user['id'];
  $.cookie(userIdCN, userId, { "expires": 1 });
  userName = _user['name'];
  userColor = _user['color'];
  /* end set User Info */

  \$signUpForm.off();
  \$signUpDOM.remove();

  setMainEvents();
}
/* end login */







/* main routine */
var \$codeRowTmp = \$codeViewDOM.find(".code_row").remove().removeClass("template"),
    \$userInputForm = \$("#user_input_form"),
    \$userInput = \$("#user_input_field > input"),
    \$codeViewField = \$("#code_view_field");
function setMainEvents(){
  log("set Main Events", userId);

  resetUserInput();
  setUserInfo2UI();
  getCodesInRoom();

  \$userInputForm.on("submit", function(_e){
    _e.preventDefault();
    postCode();
    return false;
  });
}

function resetUserInput(){
  \$userInput.val("");
}

function setUserInfo2UI(){
  \$("#user_ico").css({"background": userColor}).text(userName);
}

function getCodesInRoom(){
  post({"url": "$api_code?room_id="+roomId, "type": "get", "query": {},
    "success": function(_data){
      log("success get codes "+roomId, _data);
      setRecievedCodes(_data['data']);
    },
    "fail": function(_data){
      log("fail get codes "+roomId, _data);
    },
    "complete": function(_data){ /* nothing to do. */ }
  });
}

function setRecievedCodes(_codes){
  for(var i in _codes){
    addRecievedCode(_codes[i]);
  }
}

function addRecievedCode(_code){
  var \$codeRow = createCodeRow(_code['code']);
  \$codeRow.appendTo(\$codeViewField);
  prettyPrint();
}

function createCodeRow(_codeStr){
  var \$codeRow = \$codeRowTmp.clone();
  \$codeRow.html("<code class='prettyprint'>" + _codeStr + "</code>");
  return \$codeRow;
}

function postCode(){
  var codeText = \$userInputForm.find('#user_input_field > input').val()
                .replace(/&/g,"&amp;")
                .replace(/ /g,"&nbsp;")
                .replace(/"/g,"&quot;")
                .replace(/'/g,"&#039;")
                .replace(/</g,"&lt;")
                .replace(/>/g,"&gt;"),
      postData = { "code": codeText, "user_id": userId, "room_id": roomId };
  post({"url": "$api_code", "type": "post", "query": postData,
    "success": function(_data){
      log("success post code", _data);
      succeedPostCode(_data['data']);
    },
    "fail": function(_data){
      log("fail post code", _data);
      alert("Failed post code");
    },
    "complete": function(_data){ /* nothing to do. */ }
  });
}

function succeedPostCode(_code){
  resetUserInput();
  addRecievedCode(_code);
}
/* end main routine */

__END__
);
