<div id="lobby_back" class="issue">
  <div id="lobby" class="bg-default">
    <div id="lobby_title">Relay Programming</div>

    <div id="lobby_rooms">
      <table id="lobby_table" class="table table-bordered table-hover">
        <thead>
          <tr> <th class="rnum">No.</th><th class="issue">課題</th> </tr>
        </thead>
        <tbody>
          <tr>
            <td class="rnum">1</td>
            <td class="issue">問題あ</td>
          </tr>
          <tr>
            <td class="rnum">1</td>
            <td class="issue">問題あ</td>
          </tr>
          <tr>
            <td class="rnum">1</td>
            <td class="issue">問題あ</td>
          </tr>
          <tr>
            <td class="rnum">1</td>
            <td class="issue">問題あ</td>
          </tr>
          <tr>
            <td class="rnum">1</td>
            <td class="issue">問題あ</td>
          </tr>
          <tr>
            <td class="rnum">1</td>
            <td class="issue">問題あ</td>
          </tr>
          <tr>
            <td class="rnum">1</td>
            <td class="issue">問題あ</td>
          </tr>
          <tr>
            <td class="rnum">1</td>
            <td class="issue">問題あ</td>
          </tr>
          <tr>
            <td class="rnum">1</td>
            <td class="issue">問題あ</td>
          </tr>
          <tr>
            <td class="rnum">1</td>
            <td class="issue">問題あ</td>
          </tr>
          <tr>
            <td class="rnum">1</td>
            <td class="issue">問題あ</td>
          </tr>
          <tr>
            <td class="rnum">1</td>
            <td class="issue">問題あ</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div id="lobby_create_room_area">
      <input id="newIssueText" placeholder="新しい部屋の課題" />
      <input id="createRoomBtn" class="btn btn-info" type="button" value="CREATE" />
    </div>
  </div>
</div>



<?php
$api_user = $this->url('api/default', array('controller' => 'user'));
$api_code = $this->url('api/default', array('controller' => 'code'));
$api_chat = $this->url('api/default', array('controller' => 'chat'));
$api_room = $this->url('api/default', array('controller' => 'room'));
$api_member = $this->url('api/default', array('controller' => 'member'));
$api_roomst = $this->url('api/default', array('controller' => 'roomst'));

$this->inlineScript()->appendScript(
<<<__END__

/* declare members */
/* end declare members */


/* init */
(function main(){
  // TODO:
})();

__END__
);
